const MOCK_DATA = [
  {
    "Id": 1,
    "FirstName":"Harman",
    "LastName":"Sidhu",
    "Age": 20,
    "Country": "France",
    "Email": "harman@barusahib.org",
    "Address": "Bathinda",
    "Options": 'Options',
  },
  {
    "Id": 2,
    "FirstName": "Jashan",
    "LastName": "Singh",
    "Age": 69,
    "Country": "Brazil",
    "Email": "jashan@barusahib.org",
    "Address": "Mansa",
    "Options": 'Options',
  },
  {
    "Id": 3,
    "FirstName": "Surbhitraj",
    "LastName": "Bains",
    "Age": 22,
    "Country": "UAE",
    "Email": "surbhitraj89@gmail.com",
    "Address": "Dwarka",
    "Options": 'Options',
  },
  {
    "Id": 4,
    "FirstName": "Ramesh",
    "LastName":"Kumar",
    "Age": 27,
    "Country": "Australia",
    "Email": "kumarramesh7@gmail.com",
    "Address": "Sydney",
    "Options": 'Options',
  },
  {
    "Id": 5,
    "FirstName": "Zakir",
    "LastName":"Khan",
    "Age": 35,
    "Country": "Russia",
    "Email": "zakir123456@gmail.com",
    "Address": "Moscow",
    "Options": 'Options',
  },
  {
    "Id": 6,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 7,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 8,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 9,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 10,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 11,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 12,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 13,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 14,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
  "Id": 15,
  "FirstName": "Jordan",
  "LastName":"Peterson",
  "Age": 43,
  "Country": "Canada",
  "Email": "mr.peterson@gmail.com",
  "Address": "Toronto",
  "Options": 'Options',
  },
  {
    "Id": 16,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 17,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 18,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 19,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 20,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 21,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 22,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 23,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 24,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 25,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 26,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 27,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 28,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 29,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 30,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 31,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 32,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 33,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 34,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 35,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 36,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 37,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 38,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 39,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 40,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 41,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 42,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 43,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 44,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 45,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 46,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 47,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 48,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 49,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  {
    "Id": 50,
    "FirstName": "Jordan",
    "LastName":"Peterson",
    "Age": 43,
    "Country": "Canada",
    "Email": "mr.peterson@gmail.com",
    "Address": "Toronto",
    "Options": 'Options',
  },
  
]

export default MOCK_DATA;